# Generated by Django 4.0.4 on 2022-05-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('CustomerID', models.AutoField(primary_key=True, serialize=False)),
                ('Country', models.CharField(max_length=15)),
                ('CustomerName', models.CharField(max_length=40)),
                ('Gender', models.CharField(max_length=10)),
                ('Phone', models.CharField(max_length=15)),
                ('PostalCode', models.CharField(max_length=15)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('SalesPersonID', models.AutoField(primary_key=True, serialize=False)),
                ('SalesPersonName', models.CharField(max_length=40)),
                ('Title', models.CharField(max_length=25)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('OrderDetailID', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('sales', models.PositiveIntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('OrdersID', models.AutoField(primary_key=True, serialize=False)),
                ('SalesDate', models.DateTimeField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('Category', models.CharField(max_length=40)),
                ('Product', models.CharField(max_length=40)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('StoreID', models.AutoField(primary_key=True, serialize=False)),
                ('Region', models.CharField(max_length=10)),
                ('Store', models.CharField(max_length=40)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
            ],
            options={
                'managed': False,
            },
        ),
    ]
