# Generated by Django 3.2.13 on 2022-06-01 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.AutoField(primary_key=True, serialize=False)),
                ('Country', models.CharField(max_length=15)),
                ('CustomerName', models.CharField(max_length=40)),
                ('Gender', models.CharField(max_length=10)),
                ('Phone', models.CharField(max_length=15)),
                ('PostalCode', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('SalesPersonID', models.AutoField(primary_key=True, serialize=False)),
                ('SalesPersonName', models.CharField(max_length=40)),
                ('Title', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrdersID', models.AutoField(primary_key=True, serialize=False)),
                ('SalesDate', models.DateTimeField()),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.customer')),
                ('SalesPerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('Category', models.CharField(max_length=40)),
                ('Product', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('StoreID', models.AutoField(primary_key=True, serialize=False)),
                ('Region', models.CharField(max_length=10)),
                ('Store', models.CharField(max_length=40)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('OrderDetailID', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.PositiveSmallIntegerField()),
                ('Sales', models.FloatField()),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.order')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.product')),
                ('Store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.store')),
            ],
        ),
    ]
