# Generated by Django 3.2.13 on 2022-06-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='SalesDate',
            field=models.DateField(),
        ),
    ]
