# Generated by Django 4.0.4 on 2022-05-09 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='quantity',
            new_name='Quantity',
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='sales',
            new_name='Sales',
        ),
    ]
